### ISSUE TITLE
Uncaught RangeError: Offset is outside the bounds of the DataView

### ISSUE THREAD

**Issue by dpietrzyk** [ericnograles/browser-image-resizer#11]
Hi! I've got a problem with a few files.. :/  

Steps to reproduce:

1. Download and unzip this [file](https://drive.google.com/open?id=1g09pT1LaciZ_AzY00p8xATxYo-2N439p) - ([virus scans](https://www.virustotal.com/gui/file/7988e257f4226524d564e4e2adad79057d6b872dc0115236d52cb00ffb5d3370/detection))
1.  Go to: [demo page](https://codesandbox.io/s/nroxwpn21p)
2. Upload image from step 1
3. Open dev console and see the error ;) 
![image](https://user-images.githubusercontent.com/32246156/60363476-fa735880-99e3-11e9-99b2-a178292f4f3f.png)

After passing this image via e.g. [tinyPNG](https://tinypng.com/) everything works fine.
Can u help me with that? 
Thanks in advance!

**Comment by otaviosoares** [comment]
I have the same problem. Did you find any solution?
