### ISSUE TITLE
Syntax error in IE11 in version 2.1.0

### ISSUE THREAD

**Issue by vieira** [ericnograles/browser-image-resizer#16]
Hello,

Since version 2.1.0 IE11 throws a syntax error when executing the plugin.

To reproduce it's enough to copy the code from `dist/index.js` and paste in the IE11 console.

I am not sure if this is something related with the new depedency `exifreader` that was added with 2.1.0 or something else.

If there is anything else I can to help, just let me know.

Thanks for your work.

Have a nice week!

**Comment by ericnograles** [comment]
Thanks for the info @vieira. Most likely it's `exifreader` or how we implemented it.

I unfortunately don't have a Windows machine handy, would you mind pasting the error trace here from your IE11 console?

**Comment by mattiasw** [comment]
Maintainer of ExifReader here. You are correct. It turned out Babel did not handle everything for IE11. I rewrote some parts and there is now a new release (2.13.1) that should work better. Please update the dependency and tell me if there is anything more I can help you with.

**Comment by ericnograles** [comment]
Sorry for the delay here @vieira; finally got around to bumping this per @mattiasw. v2.1.2 of this library should be landing in NPM shortly.
