### ISSUE TITLE
is there a way to clean the cache of first Big image blob ?

### ISSUE THREAD

**Issue by Aarbel** [ericnograles/browser-image-resizer#18]

**Comment by ericnograles** [comment]
@Aarbel sorry for the delay, just getting caught up on this library again.

By cleaning the cache of the first image blob, do you mean that an image you downscaled sticks around in memory and is causing you trouble?

**Comment by ericnograles** [comment]
I think I see what you mean -- everytime we call the operation, we recreate elements. See my newly merged PR #26. I'll cut a patch version shortly to NPM.

**Comment by ericnograles** [comment]
@Aarbel please grab v2.1.3 from NPM, I think that should address this issue. Please comment if you continue to have problems, and we can reopen a new issue. Thanks for your patience!
