### ISSUE TITLE
debug statement in build?

### ISSUE THREAD

**Issue by acomito** [ericnograles/browser-image-resizer#2]
I'm running into a debug statement, with debug turned off?

"browser-image-resizer": "^1.1.1",

**Comment by ericnograles** [comment]
@acomito ah, good catch.  Will patch that up later today, thanks for reporting the issue!

**Comment by jperasmus** [comment]
Hi, have you published the fix yet because I did a new install from npm now and still getting the `debugger` on v1.1.2?

**Comment by ericnograles** [comment]
@jperasmus ah yes sorry about that, had some hanging ones out there.  I just pushed out `v1.1.3`, check that one out and let me know if you have any trouble.

**Comment by jperasmus** [comment]
Boom! Brilliant! Thanks, for quick turnaround, it is working 👍🏼
