### ISSUE TITLE
autoRotate: false fails

### ISSUE THREAD

**Issue by chriscdn** [ericnograles/browser-image-resizer#24]
Setting `autoRotate: false` prevents the promise `resolve` function from being called.

**Comment by ericnograles** [comment]
@chriscdn I unfortunately was unable to replicate using this code:

```vue
    async onChange(event) {
      let image = await readAndCompressImage(event.target.files[0], { autoRotate: false });
      let base64Image = await this.convertToBase64(image);
      this.image = base64Image;
    }
```

I'm locally testing on a macOS environment, and confirmed functionality on Chrome, Safari, and Firefox.

Can you send me details of your local environment? Thanks!

**Comment by chriscdn** [comment]
I regret I don't recall the test case or what I saw when I reported this.  Apologies for wasting your time.
