### ISSUE TITLE
EXIF Data from mobile photo libraries don't appear to be respected/understood

### ISSUE THREAD

**Issue by ericnograles** [ericnograles/browser-image-resizer#27]
# Details

- Tested on iPhone XR
    - Landscape photo doesn't rotate properly

**Comment by ericnograles** [comment]
Root cause: https://stackoverflow.com/questions/57942150/file-upload-and-exif-in-mobile-safari

It appears that in "High Efficiency" mode on an iOS camera, EXIF data is stripped. Will just need to advise people of this.

**Comment by ericnograles** [comment]
![image](https://user-images.githubusercontent.com/6023705/87861285-d2b6a180-c912-11ea-9c44-d29c784cb783.png)

**Comment by Aarbel** [comment]
@ericnograles https://github.com/blueimp/JavaScript-Load-Image seems to manage it well.

**Comment by Aarbel** [comment]
Can you fix it on this lib ?

**Comment by Aarbel** [comment]
@ericnograles did you fixed it ?

**Comment by Aarbel** [comment]
@ericnograles sorry i have an auto reminder for this ticket, is the image oirentation supported now ?

**Comment by ericnograles** [comment]
@Aarbel It's now fixed thanks to the latest version of ExifReader! Please check v2.3.2 from NPM or JS CDN
