### ISSUE TITLE
Should reject readAndCompressImage's promise when reader or img encounter error

### ISSUE THREAD

**Issue by jasonkit** [ericnograles/browser-image-resizer#28]
Right now, if someone feed in a corrupted image file, readAndCompressImage's promise will never finish.

**Comment by ericnograles** [comment]
Thanks for the contribution @jasonkit -- I did a recent refactor which also addresses this -- if you have a chance, can you re-test with `v2.2.0` and lmk if it behaves as expected? Thanks!

**Comment by jasonkit** [comment]
@ericnograles 
No, it still not working, I think you need to add `onerror` to `img` and `reader` in `readAndCompressImage` and call `reject` there as well. (you can refer to my PR: https://github.com/ericnograles/browser-image-resizer/pull/29/files)

**Comment by ericnograles** [comment]
Ah I see. Let me get those changes in this week and I'll send to you for review if that's ok?

**Comment by ericnograles** [comment]
@jasonkit merged master into your branch and reinstated your changes -- pushed to PR #29, can you review when you get a minute? Just wanna make sure you get credit for this PR in GitHub.

**Comment by ericnograles** [comment]
@AdamStone oops, that was a miss. Will merge and cut a new release in the next day or so.
