### ISSUE TITLE
Image upload failed whenever autoRotate is false false

### ISSUE THREAD

**Issue by pritam19798** [ericnograles/browser-image-resizer#30]
```
    quality: 0.5,
    maxWidth: 800,
    maxHeight: 600,
    autoRotate: false,
```

I am using this config and unable the complete . when autoRotate is set to false readAndCompressImage's promise is not finishing . But when autoRotate is set true it is working.

**Comment by ericnograles** [comment]
@pritam19798 I think the latest release `v2.2.0` should address this. Can you re-test with that version and lmk if you're still having issues? Thank you!

**Comment by pritam19798** [comment]
Yes, it is working now. Great Work !!
