### ISSUE TITLE
Unable to readAndCompressImage multiple images at once

### ISSUE THREAD

**Issue by thefivetoes** [ericnograles/browser-image-resizer#31]
I am trying to resize an array of images, and it seems that some or all of the promises never resolve. This was working in version `2.1.0` but is no longer working in `2.1.3`. 

My code:

```js
const getResizedImage = async image => {
  return await readAndCompressImage(image, {
    quality: 0.7,
    maxWidth: 766,
    maxHeight: 476,
    mimeType: "image/png"
  });
};

const images = [file, file, file];

const resizedImages = await Promise.all(images.map(image => getResizedImage(image)))
```

This seems to work if the `images` array only has a single file in it, but if I pass 2 or more files, `await Promise.all` never resolves.

**Comment by ericnograles** [comment]
@thefivetoes sorry for the delay. See the latest release `v2.2.0` -- I've refactored the library to support multi input consumers.

**Comment by ericnograles** [comment]
Some sample working code (in a Vue CLI setup): https://github.com/ericnograles/browser-image-resizer/blob/master/tests/bir-vue/src/App.vue
