### ISSUE TITLE
Incorrect image transformation for few EXIF orientations

### ISSUE THREAD

**Issue by davpsh** [ericnograles/browser-image-resizer#34]
The problem is reproduced on any version of the module.

I tested auto-rotation using an image with all possible EXIF orientations and found that some of them are not handled (transformed) correctly.

Here is a list of EXIF orientations from my tests with handle results and [original image without EXIF orientation](https://user-images.githubusercontent.com/6121462/104208852-91d3bb80-5463-11eb-96da-525dc08d72fd.jpg):

ID | Orientation | Image | Correctly transformed
------------ | ------------- | ------------- | -------------
1 | Horizontal (normal) | [orientation-1](https://user-images.githubusercontent.com/6121462/104206680-68666000-5462-11eb-89c6-964766bcd4b8.jpg) | :heavy_check_mark:
2 | Mirror horizontal | [orientation-2](https://user-images.githubusercontent.com/6121462/104206674-67353300-5462-11eb-8b13-b48e28a25ceb.jpg) | :heavy_check_mark:
3 | Rotate 180 | [orientation-3](https://user-images.githubusercontent.com/6121462/104206672-669c9c80-5462-11eb-9446-fca77fe22a96.jpg) | :heavy_check_mark:
4 | Mirror vertical | [orientation-4](https://user-images.githubusercontent.com/6121462/104206671-669c9c80-5462-11eb-9709-974658fbe9ee.jpg) | :heavy_check_mark:
5 | Mirror horizontal and rotate 270 CW | [orientation-5](https://user-images.githubusercontent.com/6121462/104206668-66040600-5462-11eb-857b-655379d01093.jpg) | :heavy_check_mark:
6 | Rotate 90 CW | [orientation-6](https://user-images.githubusercontent.com/6121462/104206665-656b6f80-5462-11eb-95f5-61adc3b72d86.jpg) | :x:
7 | Mirror horizontal and rotate 90 CW | [orientation-7](https://user-images.githubusercontent.com/6121462/104206663-64d2d900-5462-11eb-9b05-4501d6bbe1ae.jpg) | :heavy_check_mark:
8  | Rotate 270 CW | [orientation-8](https://user-images.githubusercontent.com/6121462/104206657-63091580-5462-11eb-93cf-d1c1b3a82769.jpg) | :x:

**Comment by davpsh** [comment]
After some research, I found that the problem is more complex than few incorrect transformations.

Presented data are invalid and should be ignored.
I'll try to describe problem detailed as soon as possible.

I'll close referenced PR that doesn't fixes problem.

**Comment by ericnograles** [comment]
Thanks @davpsh -- if you have sample images that you can share, I can help troubleshoot this

**Comment by otaviosoares** [comment]
I fixed it here https://github.com/otaviosoares/browser-image-resizer/commit/31c6a93e4e5402bb11129f1e6790df3d345bfa32 

It's a very poor implementation tho. I wanted to open a PR but I didn't have the time.

**Comment by tamaina** [comment]
Is there any progress? Or should I fork it?

**Comment by ericnograles** [comment]
Will take a look at these, just bumped the library to the latest ExifReader so I'm wondering if the old one had some idiosyncracies.

**Comment by ericnograles** [comment]
@davpsh I believe the bump to ExifReader may have addressed the two cases above, screenshots below

## Rotate 270 CW

![image](https://user-images.githubusercontent.com/6023705/190903440-c8814995-9d97-46fc-8d00-4e583144e67c.png)

## Rotate 90 CW

![image](https://user-images.githubusercontent.com/6023705/190903459-0615c22c-51f3-4a0b-8c72-1bf02b6da95d.png)

Please review the latest (v2.3.0) and lmk if you see the same or continue to see issues. Thanks!

**Comment by ericnograles** [comment]
@davpsh Looks like it may have been the older version of ExifReader we were using. I see the autoRotate transformations working (used your samples above):

## 90 CW

![image](https://user-images.githubusercontent.com/6023705/190903555-0e431142-a918-4941-a0d8-ac8680ce7e70.png)

## 270 CW

![image](https://user-images.githubusercontent.com/6023705/190903570-a37500a7-b2a6-4440-b223-6c7dcd399804.png)

If you grab the latest from NPM (v2.3.0) it should reflect these changes. lmk if you continue to see any issues, thanks!

**Comment by ericnograles** [comment]
Correction, latest is v2.3.1

**Comment by ericnograles** [comment]
Further testing results: NPM version should work fine, the UMD one strangely does not work -- will need to see what's going wrong there, I suspect it might be the dependency that simulates Node.js buffers in browser.

**Comment by ericnograles** [comment]
Update: It appears we may not need ExifReader anymore, all browsers should now auto rotate images based on their EXIF. Will be testing a branch without ExifReader so we can really pare down the size of this library https://aws.amazon.com/blogs/machine-learning/how-an-important-change-in-web-standards-impacts-your-image-annotation-jobs/

**Comment by ericnograles** [comment]
Tested across all browsers, all engines autoRotate by default, `exifreader` and related logic removed.
