### ISSUE TITLE
Unable to use browser image resizer

### ISSUE THREAD

**Issue by ghost** [ericnograles/browser-image-resizer#41]
** Could not find a declaration file for module 'browser-image-resizer'. 'E:/Angular/travelgram/node_modules/browser-image-resizer/dist/index.js' implicitly has an 'any' type.**

Unable to user browser image resizer: even though the module is present but it is showing is not present.

Please see the video ref: https://monosnap.com/direct/qbpKBmUth9pjpobJ0HzqtlH2ATs59i

![image](https://user-images.githubusercontent.com/46995400/130211051-03ef77fc-8eaf-428b-8ebb-ae451556c000.png)

**Comment by vojtechsimetka** [comment]
Yeah there are no types, would be great to add them.

The solution for now is to define them yourself with e.g. in a file `src/@types/browser-image-resizer`
```
declare module 'browser-image-resizer' {
  interface Config {
    quality: number
    maxWidth: number
    maxHeight: number
    autoRotate: boolean
    debug: boolean
    mimeType: 'image/jpeg' | 'image/png'
  }

  export function readAndCompressImage(file: File, userConfig?: Partial<Config>): Promise<Blob>
}
```

**Comment by ericnograles** [comment]
Types added in v2.3.0 thanks to #40, check it out and lmk if you continue to encounter issues
