### ISSUE TITLE
Transparent PNG -> jpeg shows black background.

### ISSUE THREAD

**Issue by zehawki** [ericnograles/browser-image-resizer#42]
Transparent PNG -> jpeg shows black background.

Should be white, thats the accepted approach for such conversion.

**Comment by Aarbel** [comment]
Having an option for that could be the best

**Comment by ericnograles** [comment]
Ah, good catch. I'll see if I can find a way to do this via the canvas API.

**Comment by ericnograles** [comment]
Got a fix in place, will push out v2.3.1. to address

![image](https://user-images.githubusercontent.com/6023705/190904051-5295c34f-8981-43a9-969c-807506fd5a0d.png)

**Comment by ericnograles** [comment]
Fix applied, v2.3.1 on its way to NPM

**Comment by ericnograles** [comment]
Curiously, this does not work on the UMD version from the JS CDN. Will reopen and investigate.

NPM installed versions should work fine.

**Comment by jz222** [comment]
Hi,

I'm using 2.4.1 and still have this issue. It adds a white background to PNG's with transparent background @ericnograles.
