### ISSUE TITLE
Transparency replaced with white

### ISSUE THREAD

**Issue by johnpturner8** [ericnograles/browser-image-resizer#66]
When processing a PNG with transparency, the transparency is removed and replaced with a white background, even when the mimeType is set to PNG in the config.

This seems to be caused by the fix for https://github.com/ericnograles/browser-image-resizer/issues/42, PNGs retain their transparency in the previous version.

**Comment by ericnograles** [comment]
@johnpturner8 ah good catch, let me see about plugging this bug.

**Comment by ericnograles** [comment]
Got a fix in place, will push out a new version to NPM shortly.

## Transparent PNG => mimeType: 'image/png'

<img width="1409" alt="image" src="https://user-images.githubusercontent.com/6023705/192121212-a32644bf-a693-4781-86a2-03c4ef0fcfe5.png">

## Transparent PNG => mimeType: 'image/jpeg'

<img width="1371" alt="image" src="https://user-images.githubusercontent.com/6023705/192121249-2e0d1f01-6d52-4c90-8eb8-eb3ed88bb0a5.png">

## JPEG => mimeType: 'image/jpeg'

<img width="1400" alt="image" src="https://user-images.githubusercontent.com/6023705/192121256-0a8cf356-3948-4760-9c4a-8f74977a21c4.png">

**Comment by jz222** [comment]
Hi,

I'm using 2.4.1 and still have this issue. It adds a white background to PNG's with transparent background @ericnograles.

**Comment by ericnograles** [comment]
@jz222 huh strange, pretty sure I tested it. Did you set the mimeType to `image/png`? By default, if nothing is specified, the library assumes `image/jpeg` which will give your PNG a white background by design.
