### ISSUE TITLE
👏👏 just to thank, this lib made my day

### ISSUE THREAD

**Issue by stewwan** [ericnograles/browser-image-resizer#7]
🖖

**Comment by ericnograles** [comment]
🙏 Thanks @stewwan glad it's useful for you! I just pushed a new release (v2.0.1) that allows this to be dropped directly onto a browser (#8).

Note that if you upgrade to the new version, importing `readAndCompressImage` is slightly different -- it's an exported function now.

## v1.x

```
import readAndCompressImage from 'browser-image-resizer';
```

## v2.x

```
import { readAndCompressImage } from 'browser-image-resizer';
```
